apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-github
spec:
  package: gitlab.msp.komus.net:5050/ars/images/infra/provider-github:latest
  packagePullSecrets: 
  - name: gitlab-credentials
